#!/bin/bash
set -e

TREE=$(git write-tree)
COMMIT=$(echo "WIP" | git commit-tree $TREE)
git update-ref WS_HEAD $COMMIT

git diff --stat HEAD..WS_HEAD

josh-filter --file ws/$1.josh :/ --update refs/ws/$1/base WS_HEAD
josh-filter  :/image --update refs/ws/$1/image refs/ws/$1/base
josh-filter :/run --update refs/ws/$1/run refs/ws/$1/base

IMAGE_NAME=ws-image:$(git rev-parse refs/ws/$1/image^{tree})
if docker image inspect $IMAGE_NAME >/dev/null 2>&1; then
    echo "Image exists locally"
else
    echo "Image does not exist locally"
    git archive --format=tar $(git rev-parse refs/ws/$1/image^{tree}) | docker build --build-arg user_id=$(id -u) -f Dockerfile.dev --platform linux/amd64 -t $IMAGE_NAME -
fi

vol=$1_snapshot
docker volume remove "$vol" || true
docker volume create "$vol"
docker run --rm -v "$vol":/data busybox sh -c "chown -R $(id -u):$(id -g) /data"

git archive $(git rev-parse refs/ws/$1/run^{tree}) | docker run --rm --user $(id -u):$(id -g) -i -v "$vol":/dst busybox tar -xC /dst

docker run -it --rm -v "$vol":/home/ws -v "$PWD/build:/home/ws/build" -w /home/ws --platform linux/amd64 --user $(id -u):$(id -g) $IMAGE_NAME sh -c "bash run.sh"
