#!/bin/bash
set -e
josh-filter --file ws/posix.josh :/ --update refs/ws/posix/base
josh-filter  :/image --update refs/ws/posix/image refs/ws/posix/base

IMAGE_NAME=ws-image:$(git rev-parse refs/ws/posix/image^{tree})
if docker image inspect $IMAGE_NAME >/dev/null 2>&1; then
    echo "Image exists locally"
else
    echo "Image does not exist locally"
    git archive --format=tar $(git rev-parse refs/ws/posix/image^{tree}) | docker build --build-arg user_id=$(id -u) -f Dockerfile.dev --platform linux/amd64 -t $IMAGE_NAME -
fi

docker run -it --rm -v "$PWD:/home/jenkins" -w /home/jenkins --platform linux/amd64 --user $(id -u):$(id -g) $IMAGE_NAME sh -c "treefmt"
